name: cd-ping
on:
  push:
    branches:
      - main
    paths:
      - internal/ping/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version: '~1.19.4'
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: |
          make build-ping
          cd bin && zip ping.zip ping
      - name: Push to S3
        run: aws s3 cp bin/ping.zip "s3://dakotalillie-lambda-src/webping/prod/ping.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1
