name: sms-cd
on:
  push:
    branches:
      - ci
#    paths:
#      - cmd/sms/**/*.go
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version: '~1.19.4'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.6'
          terraform_wrapper: false
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          go get -t ./cmd/sms
          pip install terraform-local
      - name: Setup test infrastructure
        run: |
          make build-sms
          make start-sms
        env:
          TF_VAR_personal_phone_number: ${{ secrets.PERSONAL_PHONE_NUMBER }}
          TF_VAR_twilio_account_sid: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TF_VAR_twilio_auth_token: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TF_VAR_twilio_phone_number: ${{ secrets.TWILIO_PHONE_NUMBER }}
      - name: Run tests
        run: go test -v ./cmd/sms
        env:
          # The values for these credentials aren't used by LocalStack, they just need to be set so that the Go SDK
          # doesn't complain
          AWS_ACCESS_KEY_ID: foo
          AWS_SECRET_ACCESS_KEY: bar
          AWS_REGION: us-east-1
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
